[project]
name = "ramdisk-save"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sawada", email = "use.github.mail@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "black",
    "isort",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.6",
]


[tool.ruff.lint]
select = [
    "F",  # Flake8
    "B",  # Black
    "I",  # isort
    "E",  # error
    "W"   # warning
]
ignore = []
fixable = ["ALL"]

# isortの設定（blackスタイルでソート）
[tool.isort]
profile = "black"

# blackの設定
[tool.black]
line-length = 100
